---
title: "Import Provgiga tile level embeddings and summary"
author: "Eslam Abousamra"
date: "2025-11-13"
output:
  BiocStyle::html_document:
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 3
package: ImageFeatureTCGA
vignette: >
  %\VignetteIndexEntry{MOFA_COAD_READ}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=FALSE}
library(ImageFeatureTCGA)
library(ggplot2)
library(dplyr)
```



```{r}
import_tile_embedding <- function(slide_filenames, cancer = "TCGA_OV") {
  purrr::map(
    slide_filenames,
    ~ {
      url <- paste0(
        "https://store.cancerdatasci.org/provgigapath/tile_level/",
        cancer, "/", .x
      )
      df <- readr::read_csv(url, show_col_types = FALSE)
      df$slide_id <- .x
      df$source_file <- .x
      return(df)
    }
  ) |> setNames(slide_filenames)
}

```



```{r}

# list slides
ov_tile_files <- listProvGiga("TCGA_OV", level = "tile_level")$Filename

# select 2 slides as an example
ov_slides <- ov_tile_files[1:2]

# 3. Run the final import function
OV_tile_dfs <- import_tile_embedding(
  ov_slides,
  cancer = "TCGA_OV"
)

```

# Embedding PCA
```{r run PCA}
example_slide = OV_tile_dfs$`TCGA-13-A5FU-01Z-00-DX1.9AD9E4B9-3F87-4879-BC0F-148B12C09036.csv.gz`
# Extract embedding numbers for pca
embedding_cols <- grep("^[0-9]+$", names(example_slide), value = TRUE)
# Run PCA on each tile
pca_res <- prcomp(example_slide[, embedding_cols], scale. = TRUE)
# create pca df
pca_example_slide <- bind_cols(
  example_slide,
  as_tibble(pca_res$x)[, 1:2] |> rename(PC1 = PC1, PC2 = PC2)
)

```


```{r visualize PC}


ggplot(pca_example_slide, aes(PC1, PC2)) +
  geom_point(alpha = 0.6, size = 1) +
  theme_minimal() +
  labs(title = "Tile-level PCA Ovarian Cancer Embedding: Single Slide")


ggplot(pca_example_slide, aes(tile_x, tile_y, color = PC1)) +
  geom_point(size = 1) +
  scale_color_viridis_c() +
  coord_equal() +
  theme_minimal() +
  labs(title = "Tissue layout colored by PCA1")

```




