---
title: "MOFA Analysis of Colorectal Cancer WSI and RNASeq"
author: "Eslam Abousamra"
date: "2025-11-13"
output:
  BiocStyle::html_document:
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 3
package: imageFeatureTCGA
vignette: >
  %\VignetteIndexEntry{MOFA_COAD_READ}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Libraries

```{r load_packages, message=FALSE}
library(imageFeatureTCGA)
library(curatedTCGAData)
library(SummarizedExperiment)
library(dplyr)
library(MOFA2)
```

# Load data

```{r load embeddings}
catalog <- getCatalog("provgigapath") |> 
    dplyr::filter(Project.ID == "TCGA-COAD") |>
    dplyr::slice(1:5)
catalog
```

# Read Colon Cancer assay with curatedTCGA

```{r load_rnaseq, message=FALSE}
#------------------------------------------
# Load COAD RNASeq assay
#------------------------------------------
coad_mae <- curatedTCGAData(
    diseaseCode = "COAD",
    assays = "RNASeq2GeneNorm",
    version = "2.1.1",
    dry.run = FALSE
)
```

# Update COAD MultiAssayExperiment with linkTCGA 

```{r linktcga}
coad_mae_emb <-
    linkTCGA(coad_mae, catalog, redownload = FALSE, parallel = FALSE)

## create artificial rownames for MOFA2
rownames(coad_mae_emb[["slide_assay"]]) <-
    paste0("slide_feat_", seq_len(nrow(coad_mae_emb[["slide_assay"]])))
```

# Run MOFA

```{r run_mofa}
# Create MOFA object from MultiAssayExperiment
mofa_obj <- create_mofa_from_MultiAssayExperiment(coad_mae_emb)

# Set data options
data_opts <- get_default_data_options(mofa_obj)

# Set model options
model_opts <- get_default_model_options(mofa_obj)
model_opts$num_factors <- 15  # the default

# Set training options
train_opts <- get_default_training_options(mofa_obj)

# currently set to fast for vignette rendering speed but slow is recommended
train_opts$convergence_mode <- "fast" 

train_opts$seed <- 42

# Prepare the model
mofa_obj <- prepare_mofa(
    object = mofa_obj,
    data_options = data_opts,
    model_options = model_opts,
    training_options = train_opts
)
test_model_file <- tempfile(fileext = ".hdf5")
# Train the model
mofa_obj.trained <- run_mofa(
    mofa_obj,
    outfile = test_model_file,
    use_basilisk = TRUE
)
```

# Visualize MOFA results

```{r load and visualize the model}
mofa_object.trained <- load_model(test_model_file)

plot_variance_explained(mofa_object.trained)
```

# Session Info

```{r sessioninfo}
sessionInfo()
```


