---
title: "Point Pattern Analysis"
author: "Ilaria Billato"
date: "2025-11-13"
output:
  BiocStyle::html_document:
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 3
package: ImageFeatureTCGA
vignette: >
  %\VignetteIndexEntry{ImageFeatureTCGA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(ImageFeatureTCGA)
library(sfdep)
library(spdep)
library(SpatialFeatureExperiment)
library(SpatialExperiment)
library(ggplot2)
```

# Import data from Hovernet as SpatialFeatureExperiment

```{r echo=TRUE}
hov_file <- paste0(
"https://store.cancerdatasci.org/hovernet/TCGA_OV/h5ad/",
"TCGA-VG-A8LO-01A-01-DX1.B39A4D64-82A1-4A04-8AB6-918F3058B83B.h5ad"
)

sfe <- HoverNet(hov_file, outClass = "SpatialFeatureExperiment") |>
import()


sfe
```


```{r}
coords <- spatialCoords(sfe)
x <- colData(sfe)$mean_intensity
y <- colData(sfe)$nearest_neighbor_distance  
```


# Moran’s I

```{r}
nb <- knn2nb(knearneigh(coords, k = 6))
lw <- nb2listw(nb, style = "W")
mi <- moran.test(x, lw)
print(mi)
```
```{r}
moran.plot(x, lw, labels = FALSE, main = "Moran scatterplot")
```

# Local Moran (LISA)

```{r}
lisa <- localmoran(x, lw)
colData(sfe)$localI <- lisa[, "Ii"]
colData(sfe)$localI_pval <- lisa[, "Pr(z != E(Ii))"]

df_lisa <- data.frame(coords, Ii = lisa[, "Ii"])
moran <- ggplot(df_lisa, aes(x = x, y = y, color = Ii)) +
  geom_point(size = 0.5) +
  scale_color_viridis_c() +
  theme_minimal() +
  ggtitle("Local Moran's I")

moran
```

# Geary’s C (globale)

```{r}
gc <- geary.test(x, lw)
print(gc)

gc_mc <- geary.mc(x, lw, nsim = 999)
print(gc_mc)
```

# Local Spatial Heteroscedasticity (LOSH)


```{r}
losh <- losh(x, nb, lw$weights)
colData(sfe)$losh <- losh$hi           # valore LOSH
colData(sfe)$losh_z <- losh$z_hi       # z-score
colData(sfe)$losh_var <- losh$var_hi   # varianza

losh_pvals <- 2 * (1 - pnorm(abs(losh$z_hi)))
colData(sfe)$losh_pval <- losh_pvals

print(paste("LOSH medio:", round(mean(losh$hi, na.rm = TRUE), 4)))
print(paste("LOSH z-score medio:", round(mean(losh$z_hi, na.rm = TRUE), 4)))
print(paste("LOSH significativi (p<0.05):", sum(losh_pvals < 0.05, na.rm = TRUE)))

df_losh <- data.frame(
  x = coords[,1], 
  y = coords[,2], 
  losh = losh$hi, 
  z_score = losh$z_hi,
  pval = losh_pvals
)

p_losh <- ggplot(df_losh, aes(x = x, y = y, color = losh)) +
  geom_point(size = 0.8, alpha = 0.7) +
  scale_color_viridis_c() +
  theme_minimal() +
  ggtitle("Local Spatial Heteroscedasticity (LOSH)") 

p_losh

p_losh_z <- ggplot(df_losh, aes(x = x, y = y, color = z_score)) +
  geom_point(size = 0.8, alpha = 0.7) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 20) +
  theme_minimal() +
  ggtitle("LOSH Z-scores") 

p_losh_z
```


